# Site settings
title: How to Become a Programmer
description: > # this means to ignore newlines until "baseurl:"
  Blogs, books, tutorials, and how-tos to help with the journey towards becoming a programmer; or a software engineer.
baseurl: "/how-to-become-a-programmer" # the subpath of your site, e.g. /blog
url: "https://dan-carroll.github.io" # the base hostname & protocol for your site

author:
  name: Dan Carroll
  email: dcarroll809@gmail.com

# Markdown settings
#markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
    line_numbers: false

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Google Analytics Tracking (optional)
ga_tracking:
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

permalink: pretty
exclude:
  [
    "node_modules/",
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "script/",
    "LICENSE.txt",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
    "graphic_templates",
    "*.py",
    "*.sh",
    "*.yml",
    "package.json",
    "CNAME",
    "assets/sass"
  ]

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
